### PR TITLE
Fix tracking stopped resources

### LINKED ISSUE #114: `ha_cluster_pacemaker_resources` doesn't report stopped resources
Steps to reproduce:

1. log into a pacemaker node with the exporter running
2. add a dummy resource with `crm configure primitive test Dummy`
3. the query `ha_cluster_pacemaker_resources{resource="test"}` will return 1 line with `role="started"`
4. stop the resource with `crm resource stop test`
5. wait 5 mins for prometheus metric staleness (related #113)
6. query `ha_cluster_pacemaker_resources{resource="test"}` 

expected behaviour:
the query should return 1 line with `role="stopped"`

observed behaviour:
the query returns 0 results

### PR DESCRIPTION
**Pull request by stefanotorresi**
This PR fixes #114.
Only tested on primitive Pacemaker resources, tests on grouped ones will be performed at a later stage due to problems with the deployment repo.

### CODE REVIEW

File: collector/pacemaker/pacemaker.go [hunk 1]
```diff
@@ -95,41 +96,55 @@ func (c *pacemakerCollector) recordNodeMetrics(crmMon crmmon.Root, ch chan<- pro
 			nodeType = "unknown"
 		}
 
-		for nodeStatus, isActive := range nodeStatuses {
-			if isActive {
+		for nodeStatus, flag := range nodeStatuses {
```
Comment (MalloZup) [inline collector/pacemaker/pacemaker.go]: why we do rename it to flag?

Comment (MalloZup) [reply collector/pacemaker/pacemaker.go]: I think `flag` is to generic and I don't get the context. Can we use a better var name?

Comment (stefanotorresi) [reply collector/pacemaker/pacemaker.go]: I did this because it was confusing at first when reading this code again, due to the fact that we have the concept of "active" status, but `isActive` doesn't mean that, it means that a particular boolean value is true or not, so a more generic `flag` term is more appropriate.

Comment (MalloZup) [reply collector/pacemaker/pacemaker.go]: ok still, I don't get what the flag is signaling :grin: .

I think we need a comment what the variable is doing.. I mean in which context to node is used. I'm talking without a memory of this piece of code.

Comment (stefanotorresi) [reply collector/pacemaker/pacemaker.go]: good idea, I will add a comment explaining the flag looping, because if we forgot it already we'll certainly forget it again. :D

Comment (MalloZup) [reply collector/pacemaker/pacemaker.go]: yeah indeed :+1:

Comment (stefanotorresi) [reply collector/pacemaker/pacemaker.go]: @MalloZup I hope 9b8b8988f1df3ccdbddc10e16af2846c98934331 is clear enough, let me know if there is more we can do.

Comment (MalloZup) [reply collector/pacemaker/pacemaker.go]: looks great now. I can understand with beeing ingnorant on code I wrote time ago. that is perfect :grin:
